/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laberinto;


import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author jsh
 */
public class Ventana extends javax.swing.JFrame {

    private int contador = 0;
    private static Mapa m;
    private static Personaje jugador;
    
    
    /**
     * Creates new form Ventana
     */

    public Ventana() {
        initComponents();
        setLocationRelativeTo(null); // Esto centra la ventana en la pantalla
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ventana = new javax.swing.JTextArea();
        Boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ventana.setColumns(20);
        ventana.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        ventana.setRows(5);
        jScrollPane1.setViewportView(ventana);

        Boton.setText("Avanzar");
        Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Boton)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Boton)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActionPerformed
        try{
        jugador.mover(m);
        contador++;
        ventana.append("Turno: " + contador + " Salud: " + jugador.getSalud() + "\n");

        
        ventana.append(m.hayAdversidad() +'\n');
        
        
        if (contador % 9 == 0) {
            jugador.setSalud(jugador.getSalud() - 20);
        }
        ventana.append(m.toString() + '\n');

        if (jugador.getSActual()== m.getSFinal()) {
            ventana.append("Harry ha ganado el juego :)" + "\n");
        }

        if (jugador.getSalud() <= 0)
            ventana.append("Harry no ha conseguido salir del laberinto :( \n");
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_BotonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Ventana().setVisible(true);
            m = new Mapa(4, 4);
                
                m.aniadirPared(0, 4);
                m.aniadirPared(3, 7);
                m.aniadirPared(5, 6);
                m.aniadirPared(5, 9);
                m.aniadirPared(8, 9);
                m.aniadirPared(8, 12);
                m.aniadirPared(10, 11);
                m.aniadirPared(10, 14);
                m.aniadirPared(11, 15);
                
                m.nuevaAdversidad(new Viento("Viento Norte", 2));
                m.nuevaAdversidad(new Viento("Viento Sur", 13));
                m.nuevaAdversidad(new Dementor(6));
                m.nuevaAdversidad(new Dementor(10));
                jugador = new Personaje(m);
                ventana.append("COMIENZA LA BATALLA\n");
                ventana.append("Turno: 0 Salud: " + jugador.getSalud() + "\n");
                ventana.append(m.toString() + "\n");
            
        }
    });
}
    
        

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea ventana;
    // End of variables declaration//GEN-END:variables
}



    
    

                                       

  
     
        
       
    
    
    
   
